# app/config/security.yml


security:

  encoders:

    Symfony\Component\Security\Core\User\User: plaintext
    #KL\UserBundle\Entity\User: plaintext #on voit le mot de passe
    KL\UserBundle\Entity\User: sha512


  role_hierarchy:

    ROLE_ADMIN:       ROLE_USER

    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


  providers:

    #in_memory:

      #memory:
        #users:
          #user:  { password: userpass, roles: [ 'ROLE_USER' ] }

          #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
    main:
      id: fos_user.user_provider.username
      #entity:

        #class: KL\UserBundle\Entity\User

        #property: username

  firewalls:

    dev:

      pattern: ^/(_(profiler|wdt)|css|images|js)/

      security: false

    main:

      pattern:   ^/

      anonymous: true

      provider: main

      form_login:

        #login_path: login
        login_path: fos_user_security_login

        #check_path: login_check
        check_path: fos_user_security_check

      logout:

        #path:       logout
        path:       fos_user_security_logout

        #target:     login
        target:     fos_user_security_login

      remember_me:

        secret: 2bf17e4cc728d1828f389de63269c8166fa750c6 #secret est un parametre de parameter

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
