<?php

namespace KL\RestaurationBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllOrderedByName()
  {
    return $this->getEntityManager()
        ->createQuery(
          'SELECT p FROM KLRestaurationBundle:Commande p ORDER BY p.name ASC'
          )
        ->getResult();
  }

  public function findWithUser($id,$user)
  {
    $parameters = [
      'id' => $id,
      'user' => $user,
    ];

    $dql =  'SELECT p
             FROM KLRestaurationBundle:Commande p
             WHERE p.id = :id
             AND p.user = :user';

    return $this->getEntityManager()
        ->createQuery($dql)
        ->setParameters($parameters)
        ->getResult();
  }
}
