<?php

namespace KL\RestaurationBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM KLRestaurationBundleBundle:Produit p ORDER BY p.name ASC'
            )
            ->getResult();
    }
}
