kl_core_homepage:
    path:     /
    defaults: { _controller: KLCoreBundle:Accueil:index }

kl_core_contact:
    path:     /contact
    defaults: { _controller: KLCoreBundle:Accueil:contact }

kl_core_connect:
    path:     /connect
    defaults: { _controller: KLCoreBundle:Accueil:connect }

kl_core_inscription:
    path:     /inscription
    defaults: { _controller: KLCoreBundle:Accueil:inscription }
