kl_core_homepage:
    path:     /
    defaults: { _controller: KLCoreBundle:Accueil:index }

kl_core_contact:
    path:     /contact/
    defaults: { _controller: KLCoreBundle:Accueil:contact }

kl_core_error:
    path:     /_error/404/
    defaults: { _controller: KLCoreBundle:Accueil:error }

kl_restauration_gerant_homepage:
    path: /admin/
    defaults: { _controller: KLUserBundle:User:indexuser}

kl_restauration_user_gerant_edit:
    path:     /admin/edit/{id_user}/
    defaults:
      _controller: KLUserBundle:User:editUser
      id_user: 1
    requirements:
      id_user: \d+


kl_restauration_cuisinier_homepage:
    path:     /cuisinier/
    defaults: { _controller: KLRestaurationBundle:Cuisinier:index }

kl_restauration_cuisinier_vue_par_commande:
    path:     /cuisinier/vue_par_commande
    defaults: { _controller: KLRestaurationBundle:Cuisinier:vueparcommande }

kl_restauration_cuisinier_vue_par_produit:
    path:     /cuisinier/vue_par_produit
    defaults: { _controller: KLRestaurationBundle:Cuisinier:vueparproduit }


kl_restauration_cuisinier_faireproduit:
    path:     /cuisinier/faireproduit/{id_cuisinier}/{id}
    defaults:
        _controller: KLRestaurationBundle:Cuisinier:faireproduit
    requirements:
        id_cuisinier: \d+
        id: \d+

kl_restauration_cuisinier_historique:
    path:     /cuisinier/historique/{id_cuisinier}
    defaults:
      _controller: KLRestaurationBundle:Cuisinier:monhistorique
    requirements:
      id_cuisinier: \d+

kl_restauration_produit_fini:
    path:     /cuisinier/produitTerminer/{id}
    defaults:
        _controller: KLRestaurationBundle:Cuisinier:produitTerminer
    requirements:
        id: \d+

kl_restauration_produit_preparation_annuler:
    path:     /cuisinier/Annulation/{id}
    defaults:
        _controller: KLRestaurationBundle:Cuisinier:PreparationAnnuler
    requirements:
        id: \d+


kl_restauration_livreur_homepage:
    path: /livreur/
    defaults: { _controller: KLUserBundle:Livreur:index}

kl_restauration_livreur_en_livraison:
    path:     /livreur/{id}/{id_user}/
    defaults:
      _controller: KLUserBundle:Livreur:enLivraison
      id: 1
      id_user: 1
    requirements:
      id: \d+
      id_user: \d+

kl_restauration_livreur_livrer:
    path:     /livreur/{id}/livrer
    defaults:
      _controller: KLUserBundle:Livreur:livrer
      id: 1
    requirements:
      id: \d+

kl_restauration_user_delete:
    path:     /admin/delete/{id}/
    defaults:
        _controller: KLUserBundle:User:deleteUser
    requirements:
        id: \d+

kl_restauration_user_delete_profile:
    path:     /delete_profile/{id}/
    defaults:
        _controller: KLUserBundle:User:deleteProfile
    requirements:
        id: \d+

kl_userbundle_profile_avatar:
    path: /user_avatar/
    defaults: { _controller: KLUserBundle:User:avatar}
