kl_core_homepage:
    path:     /
    defaults: { _controller: KLCoreBundle:Accueil:index }

kl_core_contact:
    path:     /contact
    defaults: { _controller: KLCoreBundle:Accueil:contact }

kl_core_error:
    path:     /_error/404
