kl_core_homepage:
    path:     /
    defaults: { _controller: KLCoreBundle:Accueil:index }

kl_core_contact:
    path:     /contact/
    defaults: { _controller: KLCoreBundle:Accueil:contact }

kl_core_error:
    path:     /_error/404/

kl_restauration_gerant_homepage:
    path: /admin/
    defaults: { _controller: KLUserBundle:User:indexuser}

kl_restauration_user_gerant_edit:
    path:     /admin/edit/{id_user}/
    defaults:
      _controller: KLUserBundle:User:editUser
      id_user: 1
    requirements:
      id_user: \d+

kl_restauration_user_delete:
    path:     /admin/delete/{id}/
    defaults:
        _controller: KLUserBundle:User:deleteUser
    requirements:
        id: \d+
