kl_restauration_paymentcomplete:
    path:     /commande/{id}/payment/complete/
    defaults:
        _controller: KLRestaurationBundle:Commande:paymentComplete
    requirements:
        id: \d+

kl_restauration_paymentcancel:
    path:     /commande/payment/{id}/cancel/
    defaults:
        _controller: KLRestaurationBundle:Commande:paymentCancel
    requirements:
        id: \d+
kl_restauration_paymenterror:
    path:     /commande/payement/error/
    defaults: { _controller: KLRestaurationBundle:Commande:paymentError }

kl_restauration_commande_add:
    path:     /commande/add/
    defaults: { _controller: KLRestaurationBundle:Commande:add }

kl_restauration_commande_homepage:
    path:     /commande/
    defaults: { _controller: KLRestaurationBundle:Commande:index }

kl_restauration_listecommande_homepage:
    path:     /admin/listecommandes/
    defaults: {_controller: KLUserBundle:Gerant:indexlistecommande}

kl_restauration_commande_delete:
    path:     /admin/deletecommande/{id}/
    defaults:
        _controller: KLUserBundle:Gerant:deleteCommande
    requirements:
        id: \d+

kl_restauration_commande_edit:
    path:     /admin/editcommande/{id}/
    defaults:
        _controller: KLUserBundle:Gerant:editCommande
    requirements:
        id: \d+

kl_restauration_commande_view_admin:
    path:     /admin/commande/viewAdmin/{id}/
    defaults:
        _controller: KLUserBundle:Gerant:viewadmin
        id: 1
    requirements:
        id: \d+


kl_restauration_commande_view:
    path:     /commande/view/{id}/
    defaults:
        _controller: KLRestaurationBundle:Commande:view
        id: 1
    requirements:
        id: \d+



kl_restauration_commande_adress_add:
    path:     /commande/adressAdd/{id}
    defaults:
        _controller: KLRestaurationBundle:Commande:adressAdd
    requirements:
        id: \d+

kl_restauration_panier_homepage:
    path:     /panier/
    defaults: { _controller: KLRestaurationBundle:Panier:index }

kl_restauration_panier_add:
    path:     /panier/add/{id}/
    defaults:
        _controller: KLRestaurationBundle:Panier:add
    requirements:
        id: \d+

kl_restauration_panier_delete:
    path:     /panier/delete/{id}/
    defaults:
        _controller: KLRestaurationBundle:Panier:delete
    requirements:
        id: \d+

kl_restauration_produit_homepage:
    path:     /produit/
    defaults: { _controller: KLRestaurationBundle:Produit:index }

kl_restauration_produit_search:
    path:     /search/
    defaults: { _controller: KLRestaurationBundle:Produit:search }

kl_restauration_produit_view:
    path:     /produit/view/{id}/
    defaults:
        _controller: KLRestaurationBundle:Produit:view
        id: 1
    requirements:
        id: \d+

kl_restauration_produit_add:
    path:     /admin/produit/add/
    defaults: { _controller: KLRestaurationBundle:Produit:add }

kl_restauration_produit_edit:
    path:     /admin/produit/edit/{id}/
    defaults:
        _controller: KLRestaurationBundle:Produit:edit
    requirements:
        id: \d+

kl_restauration_produit_create:
    path:     /produit/create/{gamme}/
    defaults:
        _controller: KLRestaurationBundle:Produit:create
    requirements:
        gamme: \d+

kl_restauration_produit_delete:
    path:     /admin/produit/delete/{id}/
    defaults:
        _controller: KLRestaurationBundle:Produit:delete
    requirements:
        id: \d+

kl_restauration_produit_charger:
    path:     /produit/load/
    defaults:
        _controller: KLRestaurationBundle:Produit:load

kl_restauration_gammes_charger:
    path:     /gamme/load/{id}/
    defaults:
        _controller: KLRestaurationBundle:Produit:loadGamme
        id: 1
    requirements:
        id: \d+

kl_restauration_ingredient_homepage:
    path:     /admin/ingredient/
    defaults: { _controller: KLRestaurationBundle:Ingredient:index }

kl_restauration_ingredient_view:
    path:     /admin/ingredient/view/{id}/
    defaults:
        _controller: KLRestaurationBundle:Ingredient:view
        id: 1
    requirements:
        id: \d+

kl_restauration_ingredient_add:
    path:     /admin/ingredient/add/
    defaults: { _controller: KLRestaurationBundle:Ingredient:add }

kl_restauration_ingredient_edit:
    path:     /admin/ingredient/edit/{id}/
    defaults:
        _controller: KLRestaurationBundle:Ingredient:edit
    requirements:
        id: \d+

kl_restauration_ingredient_delete:
    path:     /admin/ingredient/delete/{id}/
    defaults:
        _controller: KLRestaurationBundle:Ingredient:delete
    requirements:
        id: \d+

kl_restauration_gamme_view:
    path:     /produit/gamme/{id}/
    defaults:
        _controller: KLRestaurationBundle:Produit:viewGamme
        id: 1
    requirements:
        id: \d+

kl_restauration_gamme_add:
    path:     /admin/produit/gamme/add/
    defaults: { _controller: KLRestaurationBundle:Produit:addGamme }

kl_restauration_gamme_edit:
    path:     /admin/produit/gamme/edit/{id}/
    defaults:
        _controller: KLRestaurationBundle:Produit:editGamme
    requirements:
        id: \d+

kl_restauration_gamme_delete:
    path:     /admin/produit/gamme/delete/{id}/
    defaults:
        _controller: KLRestaurationBundle:Produit:deleteGamme
    requirements:
        id: \d+
