services:
#    kl_user.example:
#        class: KL\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
     kl_restauration.LoadUser:
         class: 'KL\UserBundle\DataFixtures\ORM\LoadUser'
         tags: [doctrine.fixture.orm]

     app.form.registration:
        class: KL\UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type }
